/**
 * md-parser.js
 *
 * Parse Markdown files conforming to the documentation convention into a structured
 * doc object, and provide accessor functions. The doc object is opaque — always use
 * the exported functions, never access doc internals directly.
 *
 * Conforms to: conventions/documentation.md
 *
 * Usage:
 *   const md = require('./lib/md-parser');
 *   const doc = md.parseFile('/path/to/file.md');
 *   console.log(md.getKeywords(doc));
 */

'use strict';

const fs   = require('./fs-scan');

// Required sections per documentation convention
const REQUIRED_SECTIONS = ['Quick Start', 'Load when'];

// Sections excluded from [up] links (and, for legacy files, from TOC skip-parsing).
// Keywords/Index/Changelog are no longer part of the canonical structure
// (conventions/documentation.md) but stay listed here so files not yet
// migrated away from them still render correctly.
const TOC_EXCLUDED = new Set(['Quick Start', 'Load when', 'Keywords', 'Table of Contents', 'Index', 'Changelog']);

// Insta-TOC codeblock inserted by toMarkdown() — see conventions/documentation.md [TOC Rule].
// `title` is the only field the renderer needs; the AI Assistant never writes this block
// by hand and never edits it — it is regenerated identically on every write.
const INSTA_TOC_BLOCK = [
  '---',
  '```insta-toc',
  '---',
  'title:',
  '  name: "Table of Contents"',
  '  level: 2',
  '  center: false',
  'exclude:',
  'style:',
  '  listType:',
  'omit:',
  'levels:',
  '  min:',
  '  max:',
  '---',
  '```',
];

// ---------------------------------------------------------------------------
// Internal — anchor generation (VS Code rules)
// ---------------------------------------------------------------------------

function _toAnchor(name) {
  return name
    .toLowerCase()
    .replace(/ /g, '-')
    .replace(/[^\w\-\u00C0-\u024F]/g, '')
    .replace(/'/g, '');
}

// ---------------------------------------------------------------------------
// Internal parsing
// ---------------------------------------------------------------------------

function _parse(text, filePath) {
  const lines    = text.split(/\r?\n/);
  const sections = [];

  let title          = null;
  let subtitle       = null;
  let language       = null;
  let currentSection = null;
  let inCodeBlock    = false;
  let inInstaToc     = false;
  let headerZone     = true;

  for (let i = 0; i < lines.length; i++) {
    const line    = lines[i];
    const trimmed = line.trim();

    // Skip the insta-toc codeblock entirely — generated by toMarkdown(), never
    // stored as section content and never hand-edited. See conventions/documentation.md [TOC Rule].
    if (inInstaToc) {
      if (/^`{3,}\s*$/.test(trimmed)) inInstaToc = false;
      continue;
    }
    if (!inCodeBlock && /^`{3,}insta-toc\b/.test(trimmed)) {
      inInstaToc = true;
      continue;
    }

    if (/^(`{3,}|~{3,})/.test(trimmed)) {
      inCodeBlock = !inCodeBlock;
      if (currentSection) currentSection.lines.push(line);
      continue;
    }

    if (inCodeBlock) {
      if (currentSection) currentSection.lines.push(line);
      continue;
    }

    if (!title && /^#\s+\S/.test(line)) {
      title = line.replace(/^#\s+/, '').trim();
      continue;
    }

    if (/^---+$/.test(trimmed)) continue;

    const h2Match = line.match(/^##\s+(.+)$/);
    if (h2Match) {
      headerZone = false;
      const sectionName = h2Match[1].trim();

      // Legacy tolerance: old files may still carry a hand-written/previously
      // generated "## Table of Contents" heading — skip it, never store it.
      if (sectionName === 'Table of Contents') {
        currentSection = null;
        continue;
      }

      currentSection = { name: sectionName, level: 2, startLine: i, lines: [] };
      sections.push(currentSection);
      continue;
    }

    if (headerZone && title) {
      if (trimmed === '') continue;
      if (/^\*Language:/i.test(trimmed)) { language = trimmed; continue; }
      if (subtitle === null) { subtitle = trimmed; continue; }
      continue;
    }

    // Skip [up] links — generated by toMarkdown(). Current format is the Obsidian
    // wikilink [[#Quick Start]] (see Up Link Rule; Obsidian resolves same-note heading
    // anchors verbatim, not slugified — see conventions/obsidian-links.md [Anchor Format]).
    // Older formats tolerated on read during migration: [[#Quick Start|up]] and the
    // pre-wikilink markdown forms [up](#quick-start) / [up](#table-of-contents).
    if (/^\[\[#Quick Start(\|up)?\]\]$/.test(trimmed)) continue;
    if (/^\[up\]\(#(quick-start|table-of-contents)\)/.test(trimmed)) continue;

    if (currentSection) currentSection.lines.push(line);
  }

  for (const s of sections) {
    while (s.lines.length > 0 && s.lines[s.lines.length - 1].trim() === '') {
      s.lines.pop();
    }
  }

  return { filePath, title, subtitle, language, sections };
}

// ---------------------------------------------------------------------------
// Public API — parsing
// ---------------------------------------------------------------------------

function parseFile(filePath) {
  const text = fs.readFile(filePath);
  return _parse(text, filePath);
}

function parseText(text, filePath) {
  if (typeof filePath === 'undefined') throw new Error('parseText requires a filePath argument');
  return _parse(text, filePath);
}

// ---------------------------------------------------------------------------
// Public API — accessors
// ---------------------------------------------------------------------------

function getTitle(doc)    { return doc.title    || null; }
function getSubtitle(doc) { return doc.subtitle || null; }
function getLanguage(doc) { return doc.language || null; }
function getQuickStart(doc) { return getSection(doc, 'Quick Start'); }

function getKeywords(doc) {
  const raw = getSection(doc, 'Keywords');
  if (!raw) return [];
  return raw.split(',').map(k => k.trim()).filter(Boolean);
}

function getSections(doc) {
  return doc.sections.map(s => ({ name: s.name, level: s.level, content: s.lines.join('\n') }));
}

function getSection(doc, name) {
  const s = doc.sections.find(s => s.name === name);
  return s ? s.lines.join('\n') : null;
}

function hasSection(doc, name) { return doc.sections.some(s => s.name === name); }
function getFilePath(doc) { return doc.filePath; }

// ---------------------------------------------------------------------------
// Public API — conformance
// ---------------------------------------------------------------------------

function getIssues(doc) {
  const issues = [];

  for (const required of REQUIRED_SECTIONS) {
    if (!hasSection(doc, required)) issues.push(`Missing ## ${required}`);
  }

  if (hasSection(doc, 'Keywords') && getKeywords(doc).length === 0) {
    issues.push('## Keywords section is empty');
  }

  return issues;
}

function isConformant(doc) { return getIssues(doc).length === 0; }

// ---------------------------------------------------------------------------
// Public API — mutations
// ---------------------------------------------------------------------------

function setTitle(doc, title) {
  if (typeof title !== 'string' || title.trim() === '') {
    throw new Error('setTitle: title must be a non-empty string');
  }
  doc.title = title.trim();
}

function setSubtitle(doc, value) {
  if (typeof value !== 'string') throw new Error('setSubtitle: value must be a string');
  doc.subtitle = value.trim() === '' ? null : value.trim();
}

function setLanguage(doc, value) {
  if (typeof value !== 'string') throw new Error('setLanguage: value must be a string');
  doc.language = value.trim() === '' ? null : value.trim();
}

function insertSectionAt(doc, name, content, position) {
  if (typeof name !== 'string' || name.trim() === '') {
    throw new Error('insertSectionAt: name must be a non-empty string');
  }
  if (typeof position !== 'string' || position.trim() === '') {
    throw new Error('insertSectionAt: position must be a non-empty string');
  }
  if (doc.sections.some(s => s.name === name)) return null;

  const lines = content ? content.split(/\r?\n/) : [];
  const newSection = { name, level: 2, startLine: -1, lines };

  if (position === 'beginning') { doc.sections.unshift(newSection); return null; }

  const match = position.match(/^(before|after):(.+)$/);
  if (!match) throw new Error('insertSectionAt: invalid position format: ' + position);

  const [, direction, refName] = match;
  const refIdx = doc.sections.findIndex(s => s.name === refName);
  if (refIdx === -1) return 'SECTION_NOT_FOUND:' + refName;

  const insertAt = direction === 'before' ? refIdx : refIdx + 1;
  doc.sections.splice(insertAt, 0, newSection);
  return null;
}

function deleteSection(doc, name) {
  if (typeof name !== 'string' || name.trim() === '') {
    throw new Error('deleteSection: name must be a non-empty string');
  }
  const idx = doc.sections.findIndex(s => s.name === name);
  if (idx === -1) return false;
  doc.sections.splice(idx, 1);
  return true;
}

function setSection(doc, name, content) {
  if (typeof name !== 'string' || name.trim() === '') {
    throw new Error('setSection: name must be a non-empty string');
  }
  const contentStr = typeof content === 'string' ? content : '';
  const lines = contentStr === '' ? [] : contentStr.split(/\r?\n/);

  const existing = doc.sections.find(s => s.name === name);
  if (existing) { existing.lines = lines; return; }

  const anchors = ['Index', 'Changelog'];
  let insertAt = doc.sections.length;
  for (const anchor of anchors) {
    const idx = doc.sections.findIndex(s => s.name === anchor);
    if (idx !== -1) { insertAt = idx; break; }
  }

  doc.sections.splice(insertAt, 0, { name, level: 2, startLine: -1, lines });
}

// ---------------------------------------------------------------------------
// Public API — reconstruction
// ---------------------------------------------------------------------------

function toMarkdown(doc) {
  if (!doc.title) throw new Error('toMarkdown: document has no title');

  const parts = [];

  parts.push(`# ${doc.title}`);
  parts.push('');
  if (doc.subtitle) { parts.push(doc.subtitle); parts.push(''); }
  if (doc.language) { parts.push(doc.language); parts.push(''); }

  let tocInserted = false;

  for (const s of doc.sections) {
    parts.push(`## ${s.name}`);
    if (!TOC_EXCLUDED.has(s.name)) parts.push('[[#Quick Start]]');
    if (s.lines.length > 0) parts.push(...s.lines);
    parts.push('');

    // Table of Contents is mandatory (conventions/documentation.md [Document Structure])
    // and always the insta-toc codeblock — inserted right after Load when, never
    // hand-written. Placed here rather than as a stored section so it can never
    // drift out of position or carry stale content.
    if (s.name === 'Load when' && !tocInserted) {
      parts.push(...INSTA_TOC_BLOCK);
      parts.push('');
      tocInserted = true;
    }
  }

  if (!tocInserted) {
    // No 'Load when' section — shouldn't happen in a conformant doc (getIssues
    // would already flag it), but insert at the end rather than silently drop the TOC.
    parts.push(...INSTA_TOC_BLOCK);
    parts.push('');
  }

  return parts.join('\n').trimEnd() + '\n';
}

// ---------------------------------------------------------------------------
// Exports
// ---------------------------------------------------------------------------

module.exports = {
  parseFile, parseText,
  getTitle, getSubtitle, getLanguage, getQuickStart, getKeywords,
  getSections, getSection, hasSection, getFilePath,
  getIssues, isConformant,
  setTitle, setSubtitle, setLanguage, setSection, insertSectionAt, deleteSection,
  toMarkdown,
};

// ---------------------------------------------------------------------------
// Changelog
// ---------------------------------------------------------------------------
//
// Version 1.13 - insta-toc codeblock preceded by a markdown separator
// Date: 2026-07-05
// The Insta TOC Obsidian plugin does not regenerate its rendered view unless the
// ```insta-toc codeblock is preceded by a `---` line (markdown horizontal rule) on its
// own — confirmed by testing on conventions/mcp-doc-index.md. INSTA_TOC_BLOCK now starts
// with '---'. No _parse() change needed: a standalone `---` line was already discarded
// unconditionally (pre-existing frontmatter-delimiter handling), so it round-trips
// silently. Mirrored in md-parser.cjs. See conventions/documentation.md [TOC Rule].
//
// Version 1.12 - [up] link switched to Obsidian wikilink, no alias
// Date: 2026-07-05
// [up](#quick-start) did not resolve in Obsidian: same-note heading anchors in Obsidian
// match the heading text verbatim (case, spaces), not a lowercased/hyphenated slug — see
// conventions/obsidian-links.md [Anchor Format]. Switched the generated link to the wikilink
// [[#Quick Start]] (no display-text alias — the heading name shown directly reads clearer
// than a generic "up" label). _parse() tolerates the previous [[#Quick Start|up]] and the
// original markdown-anchor forms on read. Mirrored in md-parser.cjs.
//
// Version 1.11 - Table of Contents mandatory, insta-toc auto-inserted, [up] to Quick Start
// Date: 2026-07-05
// Table of Contents is no longer optional and no longer a numbered link list: toMarkdown()
// now always inserts the insta-toc codeblock right after ## Load when (title.name/level
// generate the "## Table of Contents" heading at Obsidian render time — never written by
// hand). [up] links now point to #quick-start unconditionally (not gated on TOC presence,
// since Quick Start is always present, unlike the old TOC-conditional anchor). _parse()
// recognizes and discards the insta-toc block like it already did for [up] lines, tolerating
// both #quick-start and legacy #table-of-contents on read. _generateToc() removed — no
// longer needed. See conventions/documentation.md [TOC Rule, Up Link Rule, Document
// Structure] and conventions/mcp-doc-index.md [Design decisions]. Mirrored in md-parser.cjs.
//
// Version 1.10 - Non-English TOC heading check removed from getIssues
// Date: 2026-07-02
// The /table/i heuristic false-positived on any heading containing the substring
// "table" (e.g. "## Phase 5 - Legacy stable domains"), blocking write_section on
// unrelated documents. Removed rather than fixed — no reliable regex-only
// replacement identified; heading language is otherwise covered by the Language
// rule in conventions/documentation.md, enforced by review, not by this tool.
// Mirrored in md-parser.cjs.
//
// Version 1.9 - REQUIRED_SECTIONS reduced to Quick Start + Load when
// Date: 2026-07-01
// getIssues() no longer requires ## Keywords, ## Index, or ## Changelog.
// conventions/documentation.md now defines only Quick Start and Load when as
// mandatory sections; Table of Contents is optional; Index is eliminated;
// Changelog is fully centralized in CHANGELOG.md. Mirrored in md-parser.cjs
// (the copy actually require()'d by the MCP server at runtime).
//
// Version 1.8 - Non-English TOC heading detection in getIssues
// Date: 2026-05-31
// getIssues now reports any section whose name contains "table" (case-insensitive)
// but is not exactly "Table of Contents" as a conformance issue.
//
// Version 1.7 - TOC and [up] links generated by renderer
// Date: 2026-05-31
//
// Version 1.6 - subtitle and language support
// Date: 2026-05-31
//
// Version 1.5 - Code block fence detection in _parse
// Date: 2026-05-31
//
// Version 1.4 - insertSectionAt
// Date: 2026-05-31
//
// Version 1.3 - deleteSection
// Date: 2026-05-31
//
// Version 1.2 - toMarkdown throws on missing title
// Date: 2026-05-31
//
// Version 1.1 - Mutations
// Date: 2026-05-30
//
// Version 1.0 - Creation
// Date: 2026-05-30
